
all: ExceedsLancomSizeException Ipaddress Symbol Scope IntType Assignment Policy Host ExceedsLancomSizeException Interface Hostgroup Route Role 
IntType:
	javac -classpath . IntType.java
Symbol:
	javac -classpath . Symbol.java
Scope:
	javac -classpath . Scope.java
Assignment:
	javac -classpath . Assignment.java
Ipaddress:
	javac -classpath . Ipaddress.java
ExceedsLancomSizeException:
	javac -classpath . ExceedsLancomSizeException.java
Policy:
	javac -classpath . Policy.java
Host:
	javac -classpath . Host.java
Interface:
	javac -classpath . Interface.java
Hostgroup:
	javac -classpath . Hostgroup.java
Route:
	javac -classpath . Route.java
Role:
	javac -classpath . Role.java



clean:
	del *.class
