
all:
	javac -classpath . IntType.java
	javac -classpath . Policy.java
	javac -classpath . Symbol.java
	javac -classpath . Scope.java
	javac -classpath . Ipaddress.java
	
	javac -classpath . Host.java
	javac -classpath . Hostgroup.java
clean:
	rm -rf *.class
