
all:
	javac -classpath . IntType.java
	javac -classpath . Symbol.java
	javac -classpath . Scope.java
	javac -classpath . Assignment.java
	javac -classpath . Ipaddress.java
	javac -classpath . ExceedsLancomSizeException.java
	javac -classpath . Policy.java
	javac -classpath . Host.java
	javac -classpath . Interface.java
	
clean:
	rm -rf *.class
